name: Update Leaderboard

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update-leaderboard:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run leaderboard script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MODE: github
      run: python leaderboard.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Auto update leaderboard" || echo "No changes to commit"
        git push